apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-pod-scc
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - restricted-hostpath
  resources:
  - securitycontextconstraints
  verbs:
  - use
