apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nfs-server-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nfs-server-scc
subjects:
- kind: ServiceAccount
  name: nfs-server
